function F = CalculoRHS(Poi, Cpsi, SGtzi, Z, Cwsi, Twri, Twzi, Pcowi, nr, nz)

F(nr*nz,1) = 0;

for k = 1:nz
    for i = 1:nr
        
        i_P = (k-1)*nr + i;
        
        if i == 1
            %{
           if k == 1
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,2)*(Z(k+1)-Z(k))...
                    + (1/Cwsi(i_P))*(Twri(i_P,2)*(Pcowi(i_P+1)-Pcowi(i_P)) ...
                    + Twzi(i_P,2)*(Pcowi(i_P+nr)-Pcowi(i_P)));
            elseif k>1 && k<nz
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,2)*(Z(k+1)-Z(k))...
                    + SGtzi(i_P,1)*(Z(k-1)-Z(k))+ ...
                    (1/Cwsi(i_P))*(Twri(i_P,2)*(Pcowi(i_P+1)-Pcowi(i_P)) ...
                    + Twzi(i_P,2)*(Pcowi(i_P+nr)-Pcowi(i_P)) ...
                    + Twzi(i_P,1)*(Pcowi(i_P-nr)-Pcowi(i_P)));
            elseif k == nz
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,1)*(Z(k-1)-Z(k))...
                    + (1/Cwsi(i_P))*(Twri(i_P,2)*(Pcowi(i_P+1)-Pcowi(i_P)) ...
                    + Twzi(i_P,1)*(Pcowi(i_P-nr)-Pcowi(i_P)));
            end
            %}
            F(i_P) = 0;
        elseif i>1 && i<nr            
            if k == 1
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,2)*(Z(k+1)-Z(k))...
                    + (1/Cwsi(i_P))*(Twri(i_P,2)*(Pcowi(i_P+1)-Pcowi(i_P)) ...
                    + Twri(i_P,1)*(Pcowi(i_P-1)-Pcowi(i_P)) ...
                    + Twzi(i_P,2)*(Pcowi(i_P+nr)-Pcowi(i_P)));
            elseif k>1 && k<nz
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,2)*(Z(k+1)-Z(k))...
                    + SGtzi(i_P,1)*(Z(k-1)-Z(k))+ ...
                    (1/Cwsi(i_P))*(Twri(i_P,2)*(Pcowi(i_P+1)-Pcowi(i_P)) ...
                    + Twri(i_P,1)*(Pcowi(i_P-1)-Pcowi(i_P)) ...
                    + Twzi(i_P,2)*(Pcowi(i_P+nr)-Pcowi(i_P)) ...
                    + Twzi(i_P,1)*(Pcowi(i_P-nr)-Pcowi(i_P)));
            elseif k == nz
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,1)*(Z(k-1)-Z(k))...
                    + (1/Cwsi(i_P))*(Twri(i_P,2)*(Pcowi(i_P+1)-Pcowi(i_P)) ...
                    + Twri(i_P,1)*(Pcowi(i_P-1)-Pcowi(i_P)) ...
                    + Twzi(i_P,1)*(Pcowi(i_P-nr)-Pcowi(i_P)));
            end
        elseif i == nr
            %{
            if k == 1
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,2)*(Z(k+1)-Z(k))...
                    + (1/Cwsi(i_P))*(Twri(i_P,1)*(Pcowi(i_P-1)-Pcowi(i_P)) ...
                    + Twzi(i_P,2)*(Pcowi(i_P+nr)-Pcowi(i_P)));
            elseif k>1 && k<nz
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,2)*(Z(k+1)-Z(k))...
                    + SGtzi(i_P,1)*(Z(k-1)-Z(k))+ ...
                    (1/Cwsi(i_P))*(Twri(i_P,1)*(Pcowi(i_P-1)-Pcowi(i_P)) ...
                    + Twzi(i_P,2)*(Pcowi(i_P+nr)-Pcowi(i_P)) ...
                    + Twzi(i_P,1)*(Pcowi(i_P-nr)-Pcowi(i_P)));
            elseif k == nz
                F(i_P) = Poi(i_P)*Cpsi(i_P) + SGtzi(i_P,1)*(Z(k-1)-Z(k))...
                    + (1/Cwsi(i_P))*(Twri(i_P,1)*(Pcowi(i_P-1)-Pcowi(i_P)) ...
                    + Twzi(i_P,1)*(Pcowi(i_P-nr)-Pcowi(i_P)));
            end
            %}
            F(i_P) = 0;
        end
        
    end
    
end

end